In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Linear Regression Model
df = sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
x

# x = df.iloc[:, :-1].values
# x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
y = df[['species']]
y

# y = df.iloc[:, -1:].values
# y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le_y = LabelEncoder()
y = le_y.fit_transform(y)
y

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.20)

In [13]:
X_train

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
86            6.7          3.1           4.7          1.5
122           7.7          2.8           6.7          2.0
102           7.1          3.0           5.9          2.1
61            5.9          3.0           4.2          1.5
..            ...          ...           ...          ...
117           7.7          3.8           6.7          2.2
26            5.0          3.4           1.6          0.4
39            5.1          3.4           1.5          0.2
83            6.0          2.7           5.1          1.6
79            5.7          2.6           3.5          1.0

[120 rows x 4 columns]

In [15]:
Y_train

array([0, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 2,
       0, 2, 2, 2, 1, 0, 1, 2, 0, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 2,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 0, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 2, 0, 0, 1, 1])

In [16]:
lr = LinearRegression()
iris_model = lr.fit(X_train, Y_train)
predictions = iris_model.predict(X_test)

In [17]:
print(predictions)
print(Y_test)

[ 1.18047948e+00  2.38633044e-04 -9.50713980e-02  8.46272161e-03
 -4.13664191e-02  1.28190499e+00  1.15493818e+00  1.11243494e+00
  1.80218253e+00  1.97511654e+00  1.67972431e+00  1.73195572e-02
  1.80237201e+00  1.44088199e+00  1.99630942e+00  1.18011047e+00
  5.13212453e-02 -1.24326509e-01 -5.50147755e-02  1.37976691e+00
  1.91728571e+00 -2.24423141e-02  8.95744405e-01 -1.32027463e-02
  1.10512276e+00  1.18585694e+00 -7.83732061e-02  1.23136349e-01
  1.15831229e+00  1.12809123e-01]
[1 0 0 0 0 1 1 1 2 2 2 0 2 2 2 1 0 0 0 1 2 0 1 0 1 1 0 0 1 0]


In [18]:
from sklearn.metrics import r2_score

In [19]:
r2_score(Y_test, predictions)

0.948155358055617