In [1]:
import numpy as np

In [3]:
#Array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
#Checking Version of Numpy
print(np.__version__)

1.26.3


In [5]:
#ndarray
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#0-D Array
arr = np.array(42)
print(arr)

42


In [8]:
#1-D Array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
#2-D Array
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#3-D Array
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
#Check Dimensions of Array
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
#Higher Dimensional Arrays
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print("Number of Dimensions :", arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of Dimensions : 5


In [19]:
#Acces Array Element
arr = np.array([1,2,3,4,5])
print(arr)
print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

[1 2 3 4 5]
1
2
7


In [22]:
#Access 2-D Array
arr = np.array([[1,2,3,4,5], [10,20,30,40,50]])
print(arr)
print("2nd Element of 1st Row :", arr[0, 1])
print("5th Element of 2nd Row :", arr[1, 4])

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
2nd Element of 1st Row : 2
5th Element of 2nd Row : 50


In [2]:
#Access 3-D Array
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)
print("0th Array(Dimension) 1st Row and 2nd Element :", arr[1, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
0th Array(Dimension) 1st Row and 2nd Element : 12


In [29]:
#Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last Element from 2nd Dimension :', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last Element from 2nd Dimension : 10


In [34]:
#Slicing Arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[1 2 3 4 5 6 7]
[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [35]:
#Negative Slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[-3:-1])

[1 2 3 4 5 6 7]
[5 6]


In [37]:
#Step Slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[1:7:2])

[1 2 3 4 5 6 7]
[2 4 6]


In [38]:
#Prints every other element of the array
print(arr[::2])

[1 3 5 7]


In [43]:
#Slicing 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print("From 2nd element slice index from 1 to 4 :", arr[1, 1:4])
print("Index 2 of Both the Elements :", arr[0:2, 2])
print("Slice index 1 to 4 in both elements :", arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
From 2nd element slice index from 1 to 4 : [7 8 9]
Index 2 of Both the Elements : [3 8]
[[2 3 4]
 [7 8 9]]


In [47]:
#Data Types in Python
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [46]:
arr = np.array(['Apple', 'Banana', 'Cherry'])
print(arr)
print(arr.dtype)

['Apple' 'Banana' 'Cherry']
<U6


In [48]:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [49]:
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [51]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [52]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [53]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


In [54]:
#COPY
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [55]:
#VIEW
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [56]:
#Make Changes in VIEW
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 30

print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4  5]


In [57]:
#Check if Array Owns its Data
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [59]:
#Shape of an Array
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [61]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("Shape of Array :", arr.shape)

[[[[[1 2 3 4]]]]]
Shape of Array : (1, 1, 1, 1, 4)


In [62]:
#Reshape from 1-D to 2-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
arr1 = arr.reshape(4,3)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [64]:
#Reshape from 1-D to 3-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
arr1 = arr.reshape(2,3,2)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [65]:
#returns copy and view
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [66]:
#Unknown Dimension
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
arr1 = arr.reshape(2,2,-1)
print(arr1)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
#Flattening the Arrays
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
arr1 = arr.reshape(-1)
print(arr1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [3]:
#Iterating Arrays
arr = np.array([1,2,3])
print(arr)

for i in arr:
    print(i)

[1 2 3]
1
2
3


In [6]:
#Iterating 2-D Array
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [7]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

for i in arr:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [10]:
#Iterating 3-D Array
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)

for i in arr:
    print(i)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [11]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)

for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
#Iterating Array Using nditer()
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(arr)

for i in np.nditer(arr):
    print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8


In [13]:
#Iterating Arrays With Different DataTypes
arr = np.array([1,2,3])

for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'


In [14]:
#Iterating with Different Step Size
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

for i in np.nditer(arr[:, ::2]):
    print(i)

[[1 2 3 4]
 [5 6 7 8]]
1
3
5
7


In [18]:
#Enumerated Iteration Using ndenumerate()
arr = np.array([1,2,3])
print(arr)

for idx, i in np.ndenumerate(arr):
    print(idx, i)

[1 2 3]
(0,) 1
(1,) 2
(2,) 3


In [17]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

for idx, i in np.ndenumerate(arr):
    print(idx, i)

[[1 2 3]
 [4 5 6]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [20]:
#Joining NumPy Arrays
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([4,5,6])
print(arr2)
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [24]:
#Joining 2-D NumPy Arrays
arr1 = np.array([[1,2], [3,4]])
print(arr1)
arr2 = np.array([[5,6], [7,8]])
print(arr2)
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [25]:
#Joinign Arrays Using Stack Function
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([4,5,6])
print(arr2)
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [2]:
#Stacking Along the Rows
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [3]:
#Stacking Along the Columns
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
#Stacking Along Height
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [12]:
#Splitting NumPy Arrays
arr = np.array([1,2,3,4,5,6])
arr1 = np.array_split(arr, 3)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
#Split Into Arrays
arr = np.array([1,2,3,4,5,6])
arr1 = np.array_split(arr, 3)
print(arr1[0])
print(arr1[1])
print(arr2[2])

[1 2]
[3 4]
6


In [18]:
#Splitting 2-D Arrays
arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
arr1 = np.array_split(arr, 3)
print(arr1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [19]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
arr1 = np.array_split(arr, 3)
print(arr1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [20]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
arr1 = np.array_split(arr, 3, axis=1)
print(arr1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [21]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
arr1 = np.hsplit(arr, 3)
print(arr1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [25]:
#Searching Arrays
arr = np.array([1,2,3,4,5,4,4])
a = np.where(arr == 4)
print(a)

(array([3, 5, 6]),)


In [26]:
arr = np.array([1,2,3,4,5,6,7,8])
a = np.where(arr%2 == 0)
print(a)

(array([1, 3, 5, 7]),)


In [27]:
arr = np.array([1,2,3,4,5,6,7,8])
a = np.where(arr%2 == 1)
print(a)

(array([0, 2, 4, 6]),)


In [31]:
#searchsorted()
arr = np.array([6,7,8,9])
a = np.searchsorted(arr, 7)
print(a)

1


In [32]:
#Search from Right Side
arr = np.array([6,7,8,9])
a = np.searchsorted(arr, 7, side='right')
print(a)

2


In [33]:
#Multiple Values
arr = np.array([1,3,5,7])
a = np.searchsorted(arr, [2,4,6])
print(a)

[1 2 3]


In [34]:
#NumPy Sorting Arrays
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [35]:
arr = np.array(['Banana', 'Cherry', 'Apple'])
print(np.sort(arr))

['Apple' 'Banana' 'Cherry']


In [36]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [37]:
#Sorting 2-D Array
arr = np.array([[3,2,4], [5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [38]:
#Filtering Arrays
arr = np.array([41,42,43,44])
a = [True, False, True, False]
arr1 = arr[a]
print(arr1)

[41 43]


In [39]:
#Creating the Filter Array
arr = np.array([41,42,43,44])
filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

arr1 = arr[filter_arr]
print(filter_arr)
print(arr1)

[False, False, True, True]
[43 44]


In [40]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

arr1 = arr[filter_arr]
print(filter_arr)
print(arr1)

[False, True, False, True, False, True, False]
[2 4 6]


In [41]:
#Creating Filter Directly From Array
arr = np.array([41,42,43,44])
filter_arr = arr > 42
arr1 = arr[filter_arr]
print(arr1)

[43 44]


In [44]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = arr % 2 == 0
arr1 = arr[filter_arr]
print(arr1)

[2 4 6]


In [45]:
#Simple Arithmetic
#Addition
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

arr = np.add(arr1, arr2)
print(arr)

[30 32 34 36 38 40]


In [46]:
#Subtraction
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

arr = np.subtract(arr1, arr2)
print(arr)

[-10  -1   8  17  26  35]


In [47]:
#Multiplication
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

arr = np.multiply(arr1, arr2)
print(arr)

[ 200  420  660  920 1200 1500]


In [48]:
#Division
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 4, 10, 8, 2, 33])

arr = np.divide(arr1, arr2)
print(arr)

[ 3.33333333  5.          3.          5.         25.          1.81818182]


In [50]:
#Power
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 4, 6, 8, 2, 33])

arr = np.power(arr1, arr2)
print(arr)

[         1000        160000     729000000 6553600000000          2500
             0]


In [52]:
#Remainder
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

arr = np.mod(arr1, arr2)
print(arr)

[ 1  6  3  0  0 27]


In [53]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

arr = np.remainder(arr1, arr2)
print(arr)

[ 1  6  3  0  0 27]


In [54]:
#Quotient and Mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

arr = np.divmod(arr1, arr2)
print(arr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [2]:
#Absolute Values
arr = np.array([-1, -2, 1, 2, 3, -4])
arr1 = np.absolute(arr)
print(arr1)

[1 2 1 2 3 4]


In [3]:
#Rounding Decimals
#Truncation
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [5]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [6]:
#Rounding
arr = np.around(3.1666, 2)
print(arr)

3.17


In [7]:
#Floor
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [9]:
#Ceil
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


In [10]:
#NumPy logs
#log at Base 2
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [11]:
#log at Base 10
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [12]:
#Natural log
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [13]:
#NumPy Summations
#Summations
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1 = np.add(arr1, arr2)
print(arr1)

[5 7 9]


In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1 = np.sum([arr1, arr2])
print(arr1)

21


In [19]:
#Summation Over Axis
#axis=1 for rows & axis=0 for columns
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1 = np.sum([arr1, arr2], axis=1)
print(arr1)

[ 6 15]


In [20]:
#Cummulative Sum
arr = np.array([1,2,3])
arr1 = np.cumsum(arr)
print(arr1)

[1 3 6]


In [22]:
#Products
#It's Also Known as the Factorial
arr = np.array([1,2,3,4])
a = np.prod(arr)
print(a)

24


In [23]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

a = np.prod([arr1, arr2])
print(a)

40320


In [26]:
#Product Over an Axis
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr1 = np.prod([arr1, arr2], axis=1)
print(arr1)

[  24 1680]


In [27]:
#Cummulative Product
arr = np.array([5,6,7,8])
arr1 = np.cumprod(arr)
print(arr1)

[   5   30  210 1680]


In [28]:
#NumPy Differences
arr = np.array([10,15,25,5])
arr1 = np.diff(arr)
print(arr1)

[  5  10 -20]


In [29]:
arr = np.array([10, 15, 25,5])
arr1 = np.diff(arr, n=2)
print(arr1)

[  5 -30]


In [30]:
#NumPy Set Operations
arr = np.array([1,1,1,2,3,4,5,5,6,7])
a = np.unique(arr)
print(a)

[1 2 3 4 5 6 7]


In [34]:
#Finding Union
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

arr = np.union1d(arr1, arr2)
print(arr)

[1 2 3 4 5 6]


In [36]:
#Finding Intersection
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

arr = np.intersect1d(arr1, arr2, assume_unique=True)
print(arr)

[3 4]


In [37]:
#Finding Difference
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])

arr = np.setdiff1d(set1, set2, assume_unique=True)
print(arr)

[1 2]


In [38]:
#Symmetric Difference
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])

arr = np.setxor1d(set1, set2, assume_unique=True)
print(arr)

[1 2 5 6]
