In [12]:
from numpy import random

In [15]:
#Generate Random Number
a = random.randint(100)
print(a)

87


In [16]:
#Generate Random Float
a = random.rand()
print(a)

0.28726266077181106


In [17]:
#Generate Random Array
a = random.randint(100, size=(5))
print(a)

[30 29 67 32 42]


In [19]:
#3 rows and 5 columns
a = random.randint(100, size=(3,5))
print(a)

[[25 42  4 33 64]
 [98 41 12  9 47]
 [71 25 22 47 91]]


In [21]:
#Floats
a = random.rand(5)
print(a)

[0.93675544 0.0379609  0.9770788  0.85074612 0.22959669]


In [22]:
a = random.rand(3, 5)
print(a)

[[0.67510136 0.78211664 0.39650337 0.15808892 0.58822045]
 [0.41201481 0.9936451  0.77662465 0.63740496 0.36921389]
 [0.34759702 0.87878586 0.13223286 0.22349172 0.57183278]]


In [23]:
#Generate Random Number from Array
a = random.choice([3,5,7,9])
print(a)

5


In [24]:
a = random.choice([3,5,7,9], size=(3, 5))
print(a)

[[9 5 5 9 5]
 [5 5 7 3 5]
 [9 5 9 9 7]]


In [25]:
#Random Distribution
a = random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(a)

[5 5 5 3 5 7 3 7 7 3 7 5 7 7 7 7 7 7 5 5 7 5 3 3 7 7 7 7 7 5 5 5 5 7 7 7 5
 7 7 7 7 7 7 7 5 7 5 3 7 5 5 3 7 7 7 5 5 5 7 7 7 7 7 3 7 7 5 7 5 5 5 7 5 7
 3 3 7 7 3 3 7 3 5 7 7 7 5 5 3 3 5 7 7 5 7 7 7 7 7 5]


In [27]:
a = random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(a)

[[5 5 5 5 7]
 [7 3 7 5 7]
 [7 5 5 7 7]]
