In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

print("Array A :",a)
print("Array B :",b)

Array A : [1 2 3]
Array B : [[1 2 3]
 [4 5 6]]


In [7]:
print("A :",a)
print("a's ndim :", a.ndim)
print("a's shape :",a.shape)
print("a's size :",a.size)
print("a's dtype :",a.dtype)
print("a's itemsize :",a.itemsize)

A : [1 2 3]
a's ndim : 1
a's shape : (3,)
a's size : 3
a's dtype : int64
a's itemsize : 8


In [8]:
print("B :",b)
print("b's ndim :",b.ndim)
print("b's shape :",b.shape)
print("b's size :",b.size)
print("b's dtype :",b.dtype)
print("b's itemsize :",b.itemsize)

B : [[1 2 3]
 [4 5 6]]
b's ndim : 2
b's shape : (2, 3)
b's size : 6
b's dtype : int64
b's itemsize : 8


In [2]:
#Create Specific Array
a = np.zeros((2,3), dtype=int)
print("np.zeros((2,3)) :")
print(a)

np.zeros((2,3)) :
[[0 0 0]
 [0 0 0]]


In [11]:
b = np.ones((2,3))
print("np.ones((2,3)) :")
print(b)

np.ones((2,3)) :
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
c = np.empty((2,3))
print("np.empty((2,3)) :")
print(c)

np.empty((2,3)) :
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
d = np.arange(1, 2, 0.3)
print("np.arange(1, 2, 0.3) :")
print(d)

np.arange(1, 2, 0.3) :
[1.  1.3 1.6 1.9]


In [14]:
e = np.linspace(1, 2, 7)
print("np.linspace(1, 2, 7) :")
print(e)

np.linspace(1, 2, 7) :
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]


In [16]:
f = np.random.random((2,3))
print("np.random.random((2,3)) :")
print(f)

np.random.random((2,3)) :
[[0.18444305 0.70576    0.03068581]
 [0.41110427 0.69847774 0.98834705]]


In [18]:
#Shape and Operation
zero_line = np.zeros((1,3))
one_column = np.ones((3,1))
print("zer_line :", zero_line)
print("one_column :")
print(one_column)

zer_line : [[0. 0. 0.]]
one_column :
[[1.]
 [1.]
 [1.]]


In [20]:
a = np.array([[1,2,3], [4,5,6]])
b = np.arange(11, 20)
print("Array1 :")
print(a)
print("Array2 :")
print(b)

Array1 :
[[1 2 3]
 [4 5 6]]
Array2 :
[11 12 13 14 15 16 17 18 19]


In [21]:
b = b.reshape(3, -1)
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [22]:
c = np.vstack((a, b, zero_line))
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]


In [24]:
a = a.reshape(3, 2)
print("Array1 :")
print(a)

Array1 :
[[1 2]
 [3 4]
 [5 6]]


In [25]:
d = np.hstack((a, b, one_column))
print(d)

[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]


In [27]:
e = np.hsplit(d, 3)
print("Horizontal Split :",e)
print("Center One Array :",e[1])

Horizontal Split : [array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]
Center One Array : [[11. 12.]
 [14. 15.]
 [17. 18.]]


In [28]:
f = np.hsplit(d, (1, 3))
print("Horizontal Split :")
print(f)

Horizontal Split :
[array([[1.],
       [3.],
       [5.]]), array([[ 2., 11.],
       [ 4., 14.],
       [ 6., 17.]]), array([[12., 13.,  1.],
       [15., 16.,  1.],
       [18., 19.,  1.]])]


In [29]:
g = np.vsplit(d, 3)
print("Vertical Split :")
print(g)

Vertical Split :
[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]


In [3]:
#Index
a = np.arange(100, 200)
print("Array :")
print(a)
print(a[10])

Array :
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
110


In [35]:
b = np.arange(0, 100, 5)
print("Array :")
print(b)

Array :
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [14]:
a1 = a.reshape(10, -1)
print(a1)

[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [48]:
print("2nd Row Element :",a1[2])
print("2nd Row and 3rd Column Element :", a1[2, 3])
print("Last Row and Last Element :", a1[-1, -1])
print("Entire 2nd Row Elements :", a1[2, :])
print("Entire 3rd Column Elements :", a1[:, 3])
print("2nd and 5th Element in Row & 2nd and 4th Element in Column :")
print(a1[2:5, 2:4])

2nd Row Elemenst : [120 121 122 123 124 125 126 127 128 129]
2nd Row and 3rd Column Element : 123
Last Row and Last Element : 199
Entire 2nd Row Elements : [120 121 122 123 124 125 126 127 128 129]
Entire 3rd Column Elements : [103 113 123 133 143 153 163 173 183 193]
2nd and 5th Element in Row & 2nd and 4th Element in Column :
[[122 123]
 [132 133]
 [142 143]]


In [49]:
#Mathematics
arr = (np.random.random((5, 5)) - 0.5) * 100
print(arr)

[[ 1.45461395e+01  4.91429449e+01  1.88770702e-02  2.31027316e+01
  -1.09622094e+01]
 [ 3.03595489e+01  3.58034289e+01 -4.31452519e+01 -4.01262513e+01
  -1.07552826e+01]
 [ 4.55170190e+00  2.15974972e+01 -2.66659062e+01  2.79238721e+01
   2.42250564e+01]
 [-1.46340292e+01 -3.33707418e+01  3.85357534e+01 -4.07403406e+01
  -2.33588474e+01]
 [ 3.25751572e+01 -6.35879543e+00  4.56373225e+00 -9.27149484e+00
   9.83370510e+00]]


In [52]:
print("Minimum :",np.amin(arr))
print("Maximum :",np.amax(arr))
print("Average :",np.average(arr))
print("Sum :",np.sum(arr))
print("Sin :",np.sin(arr))

Minimum : -43.14525185391484
Maximum : 49.14294490138709
Average : 2.2956398295195957
Sum : 57.39099573798989
Sin : [[ 0.91752989 -0.90120311  0.01887595 -0.89640149  0.99944344]
 [-0.87057889 -0.94768694  0.74266772 -0.65520443  0.9712686 ]
 [-0.98711759  0.3835631  -0.99929203  0.34333154 -0.78808071]
 [-0.87908256 -0.92716643  0.74239728 -0.10019551  0.9794465 ]
 [ 0.91649559 -0.0755381  -0.98897092 -0.15268358 -0.39762515]]


In [53]:
arr = np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
add = arr + 50
print("Addition :",add)

add1 = arr + arr
print("Addition of Array :",add1)

Addition : [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
Addition of Array : [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [55]:
sub = arr - arr
print("Subtraction :",sub)

Subtraction : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [56]:
mul = arr * arr
print("Multiplication :",mul)

Multiplication : [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]


In [59]:
div = arr / arr
print("Division :",div)

Division : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [64]:
print("Square Root :")
print(np.sqrt(arr))
print()
print("Exponentials :")
print(np.exp(arr))
print()
print("Sin :")
print(np.sin(arr))
print()
print("Cos :")
print(np.cos(arr))
print()
print("Log :")
print(np.log(arr))
print()
print("Sum :")
print(np.sum(arr))
print()
print("Standard Deviation :")
print(np.std(arr))
print()

Square Root :
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894]

Exponentials :
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]

Sin :
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]

Cos :
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671


In [66]:
#Matrix
ar = np.floor((np.random.random((5, 5)) - 0.5) * 100)
print(ar)

[[ 44.  33. -19.  22.  24.]
 [ -9. -38. -36. -17.  15.]
 [ -4. -42.   8.   2. -44.]
 [  2. -38. -26. -37.   7.]
 [ 30. -49.  25. -48.  19.]]


In [68]:
print("Transpose as T :")
print(ar.T)
print()
print("Transpose :")
print(ar.transpose())

Transpose as T :
[[ 44.  -9.  -4.   2.  30.]
 [ 33. -38. -42. -38. -49.]
 [-19. -36.   8. -26.  25.]
 [ 22. -17.   2. -37. -48.]
 [ 24.  15. -44.   7.  19.]]

Transpose :
[[ 44.  -9.  -4.   2.  30.]
 [ 33. -38. -42. -38. -49.]
 [-19. -36.   8. -26.  25.]
 [ 22. -17.   2. -37. -48.]
 [ 24.  15. -44.   7.  19.]]


In [70]:
matrix_one = np.ones((5, 5))
print(matrix_one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
minus_one = np.dot(matrix_one, -1)
print(minus_one)

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


In [73]:
print(np.dot(ar, minus_one))

[[-104. -104. -104. -104. -104.]
 [  85.   85.   85.   85.   85.]
 [  80.   80.   80.   80.   80.]
 [  92.   92.   92.   92.   92.]
 [  23.   23.   23.   23.   23.]]


In [75]:
#Random Numbers
print("Random : ")
print(np.random.random(20))

Random : 
[0.7419972  0.53657522 0.0347992  0.57360629 0.16092321 0.89790897
 0.94407809 0.84548761 0.72503909 0.37076695 0.48928905 0.57460477
 0.40951487 0.08384614 0.39319067 0.49316437 0.75534055 0.56678123
 0.36389612 0.0882709 ]


In [77]:
print("Rand :")
print(np.random.rand(3,4))

Rand :
[[0.19571429 0.47628065 0.11695689 0.45228938]
 [0.2481524  0.68038353 0.66026689 0.4156201 ]
 [0.11280282 0.63101126 0.21510801 0.85694775]]


In [78]:
print("randint :")
print(np.random.randint(0, 100, 20))

randint :
[55 31 69 59 34 95 64 13 28 89 65 94 35 54 86 67  2 52 66 59]


In [80]:
print("Permutation :")
print(np.random.permutation(np.arange(25)))

Permutation :
[ 4 11  1 19  5 17  8 23  2  0 14 18 12 24  3 15 21 22 10  7 20 16 13  9
  6]
