In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# **LINEAR REGRESSION**

In [19]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [5]:
# Filter Independent Variable

x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
x.shape

(150, 4)

In [9]:
# Filter Dependent Variable

y = df['species']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [10]:
y.shape

(150,)

In [11]:
# Conver Y in numbers Encoding

from sklearn.preprocessing import LabelEncoder

In [12]:
le_y = LabelEncoder()
y = le_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
x_train

sepal_length  sepal_width  petal_length  petal_width
112           6.8          3.0           5.5          2.1
89            5.5          2.5           4.0          1.3
113           5.7          2.5           5.0          2.0
75            6.6          3.0           4.4          1.4
32            5.2          4.1           1.5          0.1
..            ...          ...           ...          ...
65            6.7          3.1           4.4          1.4
21            5.1          3.7           1.5          0.4
130           7.4          2.8           6.1          1.9
60            5.0          2.0           3.5          1.0
131           7.9          3.8           6.4          2.0

[105 rows x 4 columns]

In [15]:
x_train.size

420

In [16]:
x_test.size

180

In [17]:
y_train.size

105

In [18]:
y_test.size

45

# **LOGISTIC REGRESSION**

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
log = LogisticRegression()
log.fit(x_train, y_train)

LogisticRegression()

In [23]:
y_pred = log.predict(x_test)
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [24]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

# **CONFUSION MATRIX**

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
confusion_matrix(y_test, y_pred)

array([[14,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 17]])

In [27]:
(28/30)*100

93.33333333333333

In [28]:
log.score(x_test, y_test)

0.9555555555555556

# **KNEIGHBOURS CLASSIFIERS**

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) # distance name

In [35]:
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [36]:
y_pred_kn = classifier_knn.predict(x_test)
y_pred_kn

array([1, 0, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 0, 2, 2, 2, 0, 1, 2, 0, 2,
       2, 0, 0, 1, 2, 0, 1, 0, 0, 2, 2, 1, 0, 1, 0, 1, 2, 2, 1, 0, 2, 0,
       2])

In [37]:
# confusion matrix
confusion_matrix(y_test, y_pred_kn)

array([[14,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 17]])

In [38]:
classifier_knn.score(x_test, y_test)

0.9777777777777777

# **ACCURACY SCORE**

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y_pred_kn, y_test)

0.9777777777777777

# **NAVIASBIAS MODEL**

In [41]:
from sklearn.naive_bayes import GaussianNB

In [42]:
classifier_nb = GaussianNB()

In [43]:
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [44]:
y_pred = classifier_nb.predict(x_test)
y_pred

array([1, 0, 2, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 0, 2, 2, 2, 0, 1, 2, 0, 2,
       1, 0, 0, 1, 2, 0, 1, 0, 0, 2, 2, 1, 0, 1, 0, 1, 2, 2, 1, 0, 1, 0,
       2])

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
accuracy_score(y_pred_kn, y_test)

0.9777777777777777

In [47]:
confusion_matrix(y_test, y_pred)

array([[14,  0,  0],
       [ 0, 13,  1],
       [ 0,  1, 16]])

In [48]:
classifier_nb.score(x_test, y_test)

0.9555555555555556